export const WEBSITE_INFO = [
  "Platform Name: GoGodam",
  "Tagline: Inventory, suppliers, and deliveries—in one flow.",
  "Purpose & Overview: A multi-tenant inventory & logistics management platform designed to streamline warehouse operations, supplier tracking, and transporter routing.",
  "Target Audience & Roles:",
  "  1. Admin: Manages organizations, users, invites suppliers, and has overall system oversight and statistics access.",
  "  2. Inventory Manager: Manages products, categories, stock tracking, and places purchase orders.",
  "  3. Supplier: Reviews and confirms orders received from the inventory manager.",
  "  4. Transporter/Driver: Assigned to orders to handle deliveries, updates progress/statuses, and routes.",
  "Key Features:",
  "  - Real-time stock tracking and low-stock alerts.",
  "  - Organization creation and onboarding for team isolation.",
  "  - Order lifecycle management (created -> confirmed/approved -> in progress -> completed).",
  "  - Role-based dashboard layouts tailored specifically to each user type.",
  "  - Pre-defined test users for rapid role exploration.",
  "Technology Stack:",
  "  - Frontend & Backend Framework: Next.js (version 16) with App Router, TypeScript, and React (version 19).",
  "  - Styling: Tailwind CSS (version 4) and Vanilla CSS.",
  "  - Database & Authentication: Supabase (Auth, PostgreSQL DB, and Row Level Security).",
  "Website Navigation & Pages:",
  "  - Home page (/): Features interactive preview dashboards, core workflows list, features, and marketing information.",
  "  - Login page (/login): Simple, secure portal for role-based system access.",
  "  - Sign Up page (/signup): Portal for creating organizations and user accounts.",
  "Creator/Developers: Built by the Collaborative Development Team.",
  "Support / Contact: Users can reach out via the login help desk or system administrator.",
].join("\n");
